services:
  php:
    container_name: wpl-shared-advert-library-php
    image: ghcr.io/m0lnardaniel/php-7.4-apache
    ports:
      - "${HTTP_PORT:-8040}:80"
    volumes:
      - ./src:/var/www/html
      - ./src/env.local.php:/var/www/html/env.php:ro
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - webplus

  mysql:
    container_name: wpl-shared-advert-library-mysql
    image: mariadb:12.3
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: app
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: app
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/dump:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5m
      start_interval: 2s
    networks:
      - webplus

networks:
  webplus:
    name: webplus
